version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: mariadb_root_password
      MYSQL_DATABASE: pedelogo_catalogo
      MYSQL_USER: mariadb_user
      MYSQL_PASSWORD: mariadb_password
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mysql

  api:
    image: thsre/api-servidor:latest
    ports:
      - "30000:80"
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=pedelogo_catalogo
      - MYSQL_USER=mariadb_user
      - MYSQL_PASSWORD=mariadb_password
