version: '3'

services:
  mongodb:
    image: mongo:4.2.8
    ports:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodbuser
      - MONGO_INITDB_ROOT_PASSWORD=mongodbpwd
    volumes:
      - ./mongodb-data:/data/db

  api:
    image: thsre/api-servidor:latest
    ports:
      - "30000:80"
    environment:
      - MONGODB_URI=mongodb://mongodbuser:mongodbpwd@mongo-service:27017/admin

  mongo-service:
    image: mongo:4.2.8
    volumes:
      - ./mongodb-data:/data/db
